/*
Onboarding API


The onboarding API allows you to refer your customers and personal contacts to Brex.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Required information about the referred prospect.
 * @export
 * @interface Applicant
 */
export interface Applicant {
    /**
     * Last name of the applying customer.
     * @type {string}
     * @memberof Applicant
     */
    'last_name': string;
    /**
     * First name of the applying customer.
     * @type {string}
     * @memberof Applicant
     */
    'first_name': string;
    /**
     * Business email of the applying customer.
     * @type {string}
     * @memberof Applicant
     */
    'email': string;
}

