/*
Onboarding API


The onboarding API allows you to refer your customers and personal contacts to Brex.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { IdentityDocument } from './identity-document';
import { IdentityDocumentType } from './identity-document-type';

/**
 * 
 * @export
 * @interface BeneficialOwnerIdentityDocument
 */
export interface BeneficialOwnerIdentityDocument {
    /**
     * Country where the identity document was issued.
     * @type {string}
     * @memberof BeneficialOwnerIdentityDocument
     */
    'country': string;
    /**
     * Either a US SSN or US/international passport.
     * @type {IdentityDocumentType}
     * @memberof BeneficialOwnerIdentityDocument
     */
    'type': IdentityDocumentType;
    /**
     * US SSN or passport number.
     * @type {string}
     * @memberof BeneficialOwnerIdentityDocument
     */
    'number': string;
}

