/*
Onboarding API


The onboarding API allows you to refer your customers and personal contacts to Brex.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BeneficialOwner } from './beneficial-owner';
import { BeneficialOwnerAddress } from './beneficial-owner-address';
import { IncorporationType } from './incorporation-type';

/**
 * Information about the business the application is for.  You can optionally set the `alternate_address`, if the business has an additional address which is different from the  registration address. For instance, for international companies where their operational address may be different  than where the company was incorporated. 
 * @export
 * @interface Business
 */
export interface Business {
    /**
     * Company legal name.
     * @type {string}
     * @memberof Business
     */
    'legal_name'?: string | null;
    /**
     * 
     * @type {IncorporationType}
     * @memberof Business
     */
    'incorporation_type'?: IncorporationType;
    /**
     * Company Employer Identification Number(EIN).
     * @type {string}
     * @memberof Business
     */
    'employer_identification_number'?: string | null;
    /**
     * Business website (or link to ecommerce store for sellers).
     * @type {string}
     * @memberof Business
     */
    'website_url'?: string | null;
    /**
     * Brief description of the business activity.
     * @type {string}
     * @memberof Business
     */
    'activity_description'?: string | null;
    /**
     * 
     * @type {BeneficialOwnerAddress}
     * @memberof Business
     */
    'address'?: BeneficialOwnerAddress;
    /**
     * List of beneficial owners of the company
     * @type {Array<BeneficialOwner>}
     * @memberof Business
     */
    'beneficial_owners'?: Array<BeneficialOwner> | null;
    /**
     * 
     * @type {BeneficialOwnerAddress}
     * @memberof Business
     */
    'alternate_address'?: BeneficialOwnerAddress;
}

