/*
Onboarding API


The onboarding API allows you to refer your customers and personal contacts to Brex.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Account } from './account';
import { Application } from './application';

/**
 * Available if customer applied for Brex Cash.
 * @export
 * @interface Cash
 */
export interface Cash {
    /**
     * 
     * @type {Array<Account>}
     * @memberof Cash
     */
    'accounts'?: Array<Account> | null;
    /**
     * 
     * @type {Application}
     * @memberof Cash
     */
    'application': Application;
}

