/*
Onboarding API


The onboarding API allows you to refer your customers and personal contacts to Brex.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Applicant } from './applicant';
import { ContactPreference } from './contact-preference';
import { CreateReferralRequestBusiness } from './create-referral-request-business';

/**
 * Submit a new referral to Brex for onboarding.
 * @export
 * @interface CreateReferralRequest
 */
export interface CreateReferralRequest {
    /**
     * Referral code that attributes credit to you if the prospect signs up for a Brex account.
     * @type {string}
     * @memberof CreateReferralRequest
     */
    'referral_code': string;
    /**
     * 
     * @type {Applicant}
     * @memberof CreateReferralRequest
     */
    'applicant': Applicant;
    /**
     * 
     * @type {CreateReferralRequestBusiness}
     * @memberof CreateReferralRequest
     */
    'business'?: CreateReferralRequestBusiness;
    /**
     * 
     * @type {ContactPreference}
     * @memberof CreateReferralRequest
     */
    'contact_preference'?: ContactPreference;
}

