/*
Onboarding API


The onboarding API allows you to refer your customers and personal contacts to Brex.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DocumentType } from './document-type';

/**
 * Request for creating new document upload URL.
 * @export
 * @interface CreateDocumentRequest
 */
export interface CreateDocumentRequest {
    /**
     * Type of document being submitted. Allowable types: - ARTICLES_OF_INCORPORATION - IRS_EIN_CONFIRMATION (IRS CP 575 or 147C form) - IRS_EIN_APPLICATION (IRS SS4 form) - CERTIFICATE_GOOD_STANDING 
     * @type {DocumentType}
     * @memberof CreateDocumentRequest
     */
    'type': DocumentType;
}

