/*
Onboarding API


The onboarding API allows you to refer your customers and personal contacts to Brex.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Domestic ACH/wire instructions.
 * @export
 * @interface DomesticInstruction
 */
export interface DomesticInstruction {
    /**
     * 
     * @type {string}
     * @memberof DomesticInstruction
     */
    'account_type': string;
    /**
     * 
     * @type {string}
     * @memberof DomesticInstruction
     */
    'bank_account_number': string;
    /**
     * 
     * @type {string}
     * @memberof DomesticInstruction
     */
    'bank_routing_number': string;
    /**
     * 
     * @type {string}
     * @memberof DomesticInstruction
     */
    'beneficiary_name': string;
    /**
     * 
     * @type {string}
     * @memberof DomesticInstruction
     */
    'beneficiary_address': string;
    /**
     * 
     * @type {string}
     * @memberof DomesticInstruction
     */
    'bank_name': string;
    /**
     * 
     * @type {string}
     * @memberof DomesticInstruction
     */
    'bank_address': string;
}

