/*
Onboarding API


The onboarding API allows you to refer your customers and personal contacts to Brex.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Either a US SSN or US/international passport.
 * @export
 * @enum {string}
 */
export type IdentityDocumentType = 'SSN' | 'PASSPORT'

