/*
Onboarding API


The onboarding API allows you to refer your customers and personal contacts to Brex.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Incorporation type of the company referred.
 * @export
 * @enum {string}
 */
export type IncorporationType = 'C_CORP' | 'S_CORP' | 'B_CORP' | 'LLC' | 'LLP' | 'SOLE_PROP' | 'ORG_501C3' | 'LP'

