/*
Onboarding API


The onboarding API allows you to refer your customers and personal contacts to Brex.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DomesticInstruction } from './domestic-instruction';
import { InternationalInstruction } from './international-instruction';

/**
 * Domestic and international ACH/wire instructions.
 * @export
 * @interface Instruction
 */
export interface Instruction {
    /**
     * 
     * @type {DomesticInstruction}
     * @memberof Instruction
     */
    'domestic': DomesticInstruction;
    /**
     * 
     * @type {InternationalInstruction}
     * @memberof Instruction
     */
    'international': InternationalInstruction;
}

