/*
Onboarding API


The onboarding API allows you to refer your customers and personal contacts to Brex.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * International wire instructions.
 * @export
 * @interface InternationalInstruction
 */
export interface InternationalInstruction {
    /**
     * 
     * @type {string}
     * @memberof InternationalInstruction
     */
    'account_type': string;
    /**
     * 
     * @type {string}
     * @memberof InternationalInstruction
     */
    'swift_account_number': string;
    /**
     * 
     * @type {string}
     * @memberof InternationalInstruction
     */
    'swift_bank_number': string;
    /**
     * 
     * @type {string}
     * @memberof InternationalInstruction
     */
    'beneficiary_name': string;
    /**
     * 
     * @type {string}
     * @memberof InternationalInstruction
     */
    'beneficiary_address': string;
    /**
     * 
     * @type {string}
     * @memberof InternationalInstruction
     */
    'bank_name': string;
    /**
     * 
     * @type {string}
     * @memberof InternationalInstruction
     */
    'bank_address': string;
    /**
     * 
     * @type {string}
     * @memberof InternationalInstruction
     */
    'special_instructions': string;
}

