/*
Onboarding API


The onboarding API allows you to refer your customers and personal contacts to Brex.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Cash } from './cash';

/**
 * Array of Brex products that the customer has applied for. This is a gated feature available to select clients only.
 * @export
 * @interface Product
 */
export interface Product {
    /**
     * 
     * @type {Cash}
     * @memberof Product
     */
    'cash': Cash;
}

