/*
Onboarding API


The onboarding API allows you to refer your customers and personal contacts to Brex.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * When using `CONTROL` prong, the beneficial owner is a single individual with  significant responsibility to control, manage, or direct a legal entity customer. This includes, an executive officer or senior manager (Chief Executive Officer, Chief Financial Officer, Chief Operating Officer, President), or any other individual who regularly performs similar functions.   Under the `OWNERSHIP` prong, a beneficial owner is each individual, if any, who, directly or indirectly, through any contract, arrangement, understanding, relationship or otherwise, owns 25 percent or more of the equity interests of a legal entity customer. If a trust owns directly or indirectly, through any contract, arrangement, understanding, relationship or otherwise, 25 percent or more of the equity interests of a legal entity customer, the beneficial owner is the trustee.  Under the `BOTH` prong, the beneficial owner represents both. 
 * @export
 * @enum {string}
 */
export type Prong = 'OWNERSHIP' | 'CONTROL' | 'BOTH'

