/*
Onboarding API


The onboarding API allows you to refer your customers and personal contacts to Brex.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Product } from './product';
import { ReferralStatus } from './referral-status';

/**
 * 
 * @export
 * @interface Referral
 */
export interface Referral {
    /**
     * Unique identifier for the referral.
     * @type {string}
     * @memberof Referral
     */
    'id': string;
    /**
     * Signup URL to redirect prospects to complete their onboarding flow.  *Note*: Necessary disclosures must be shown when the prospect clicks on this link. 
     * @type {string}
     * @memberof Referral
     */
    'referral_signup_url': string;
    /**
     * The time at which this referral link expires.
     * @type {string}
     * @memberof Referral
     */
    'expires_at': string;
    /**
     * Customer\'s email address registered for the Brex application. This field is available only if there\'s a signup completed. 
     * @type {string}
     * @memberof Referral
     */
    'customer_email'?: string | null;
    /**
     * Status of the referral. `UNCLAIMED` or `EXPIRED` unless the customer completes signup. Customers are attributed once `ACTIVE` until the account is `CLOSED`.
     * @type {ReferralStatus}
     * @memberof Referral
     */
    'status': ReferralStatus;
    /**
     * 
     * @type {Array<Product>}
     * @memberof Referral
     */
    'products': Array<Product>;
}

