/*
Onboarding API


The onboarding API allows you to refer your customers and personal contacts to Brex.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Referral } from './referral';

/**
 * 
 * @export
 * @interface ReferralPage
 */
export interface ReferralPage {
    /**
     * 
     * @type {string}
     * @memberof ReferralPage
     */
    'next_cursor'?: string | null;
    /**
     * 
     * @type {Array<Referral>}
     * @memberof ReferralPage
     */
    'items': Array<Referral>;
}

